(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.

Parameter a: Prop.

Parameter b: Prop.

Parameter c: Prop.

(* Why3 assumption *)
Definition da : Prop := ~ b /\ c.

(* Why3 assumption *)
Definition db : Prop := ~ a -> ~ c.

(* Why3 assumption *)
Definition dc : Prop := c /\ (~ b \/ ~ a).

(* Why3 goal *)
Theorem InnoVeriteA : ((a -> da) /\ ((b -> db) /\ (c -> dc))) -> a.
(* Why3 intros (h1,(h2,h3)). *)
Proof.
intros (h1,(h2,h3)).

Qed.

